# Spring Boot application configuration

# Server configuration
server:
  port: 8090

# Database configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# Logging configuration
logging:
  level:
    root: INFO
mybatis:
  type-aliases-package: com.example.demo.server
  mapper-locations: classpath*:*.xml